server {
        listen 80;
        #server_name portfolio.ln-kr.ru;

        index index.html;
        location / {
                root /var/www/portfolio/build/;
        }

        location /data {
                alias /var/www/portfolio/src/assets/;
                try_files $uri $uri;
        }
}